#---------------------------------------------------#
# 配置文件需要放置在 $HOME/.config/clash/config.yml
# 或者运行目录下的config.yml
#---------------------------------------------------#
# 混合端口 HTTP和SOCKS5用一个端口
mixed-port: 7890

# 允许局域网的连接（可用来共享代理）
allow-lan: true

# 规则模式：Rule（规则） / Global（全局代理）/ Direct（全局直连）
mode: Rule

# 设置日志输出级别 (默认级别：silent，即不输出任何内容，以避免因日志内容过大而导致程序内存溢出）。
# 5 个级别：silent / error / warning / info / debug。级别越高日志输出量越大，越倾向于调试，若需要请自行开启。
log-level: info

# Clash 的 RESTful API
external-controller: '127.0.0.1:9090'

# 实验性功能
experimental:
  ignore-resolve-fail: true # 忽略 DNS 解析失败，默认值为 true

dns:
  enable: true # 是否启用 dns false
  ipv6: false
# listen: 0.0.0.0:53
  nameserver-policy:
    '*.tw': 1.1.1.1
    'testflight.apple.com': 8.8.8.8
    '*.tmall.com': 223.5.5.5
    '*.taobao.com': 223.5.5.5
    '*.alicdn.com': 223.5.5.5
    '*.aliyun.com': 223.5.5.5
    '*.alipay*.com': 223.5.5.5
    '*.alibaba*.com': 223.5.5.5
    '*.alimama*.com': 223.5.5.5
    '*.qq.com': 119.29.29.29
    '*.tencent.com': 119.29.29.29
    '*.weixin.com': 119.29.29.29
    '*.qpic.cn': 119.29.29.29
    '*.jd.com': 119.29.29.29
    '*.bilibili.com': 119.29.29.29
    'hdslb.com': 119.29.29.29
    '*.163.com': 119.29.29.29
    '*.126.com': 119.29.29.29
    '*.126.net': 119.29.29.29
    '*.127.net': 119.29.29.29
    '*.netease.com': 119.29.29.29
    '*.10010.com': 119.29.29.29
    '*.unicompayment.com': 119.29.29.29
    '*.vercel.app': 119.29.29.29
    '*.vercel.com': 119.29.29.29
    '*.ximalaya.com': 119.29.29.29
    '*.baidu.com': 180.76.76.76
    '*.bdstatic.com': 180.76.76.76
  default-nameserver:
    - 223.5.5.5 # 阿里 AliDNS
    - 119.29.29.29 # 腾讯 DNSPod DNS+
    - 8.8.8.8 # Google DNS
  enhanced-mode: redir-host
  nameserver:
    - https://dns.alidns.com/dns-query # Ali DoH
    - https://doh.pub/dns-query # Tencent DoH
    - https://dns.rubyfish.cn/dns-query # Rubyfish DoH
#   - https://doh.opendns.com/dns-query # OpenDNS DoH
  fallback:
    - https://public.dns.iij.jp/dns-query # IIJ.JP DoH
    - https://dns.cloudflare.com/dns-query # CloudFlare DoH
    - https://dns.google/dns-query # Google DoH
#   - https://dns.adguard.com/dns-query # Adguard DoH
  fallback-filter:
    geoip: true # 默认
    geoip-code: CN
    ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
      - 0.0.0.0/32
      - 127.0.0.1/32
      - 240.0.0.0/4
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
      - +.apple.com
      - +.apple-cloudkit.com
      - +.apple-mapkit.com
      - +.cdn-apple.com
      - +.mzstatic.com
      - +.microsoft.com
      - +.bing.com
      - +.linkedin.com
      - +.licdn.com

script:
  shortcuts:
    Quic: network == 'udp' and dst_port == 443