mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
ipv6: false
external-controller: '0.0.0.0:9090'
hosts:
  'router.asus.com': 192.168.186.1
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  nameserver-policy:
    '*.tmall.com': 223.5.5.5
    '*.taobao.com': 223.5.5.5
    '*.alicdn.com': 223.5.5.5
    '*.aliyun.com': 223.5.5.5
    '*.alipay*.com': 223.5.5.5
    '*.alibaba*.com': 223.5.5.5
    '*.alimama*.com': 223.5.5.5
    '*.qq.com': 119.29.29.29
    '*.tencent.com': 119.29.29.29
    '*.weixin.com': 119.29.29.29
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  fake-ip-filter: # fake ip 白名单
    - '*.lan'
    - cable.auth.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - network-test.debian.org
    - detectportal.firefox.com
    - resolver1.opendns.com
    - '*.*.*.srv.nintendo.net'
    - '*.*.stun.playstation.net'
    - xbox.*.*.microsoft.com
    - '*.*.xboxlive.com'
    - stun.*.*.*
    - stun.*.*
    - localhost.*.qq.com
    - '*.logon.battlenet.com.cn'
    - '*.logon.battle.net'
    - '*.blzstatic.cn'
    - music.163.com
    - '*.music.163.com'
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - '*.y.qq.com'
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - '*.xiami.com'
    - '*.music.migu.cn'
    - music.migu.cn
    - proxy.golang.org
    - '*.mcdn.bilivideo.cn'
    - '*.cmpassport.com'
    - id6.me
    - open.e.189.cn
    - mdn.open.wo.cn
    - auth.wosms.cn
    - '*.jegotrip.com.cn'
    - '*.icitymobile.mobi'
    - '*.pingan.com.cn'
    - '*.cmbchina.com'
    - pool.ntp.org
    - '*.pool.ntp.org'
    - ntp.*.com
    - time.*.com
    - ntp?.*.com
    - time?.*.com
    - time.*.gov
    - time.*.edu.cn
    - '*.ntp.org.cn'
    - PDC._msDCS.*.*
    - DC._msDCS.*.*
    - GC._msDCS.*.*
    - speedtest.cros.wr.pvp.net
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  fallback:
    - 8.8.8.8
    - 1.1.1.1
  fallback-filter:
    geoip: true
    geoip-code: CN
    ipcidr:
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
      - +.github.com
      - +.githubusercontent.com
