# Clash Verge DNS Config

enable: true
listen: 127.0.0.1:53
ipv6: true
prefer-h3: true
enhanced-mode: fake-ip
fake-ip-range: 198.18.0.1/16
respect-rules: true
fake-ip-filter:
  - '*.lan'
  - cable.auth.com
  - '*.msftconnecttest.com'
  - '*.msftncsi.com'
  - network-test.debian.org
  - detectportal.firefox.com
  - resolver1.opendns.com
  - '*.*.*.srv.nintendo.net'
  - '*.*.stun.playstation.net'
  - xbox.*.*.microsoft.com
  - '*.*.xboxlive.com'
  - stun.*.*.*
  - stun.*.*
  - localhost.*.qq.com
  - '*.logon.battlenet.com.cn'
  - '*.logon.battle.net'
  - '*.blzstatic.cn'
  - music.163.com
  - '*.music.163.com'
  - '*.126.net'
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - '*.kuwo.cn'
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - '*.y.qq.com'
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - '*.xiami.com'
  - '*.music.migu.cn'
  - music.migu.cn
  - proxy.golang.org
  - '*.mcdn.bilivideo.cn'
  - '*.cmpassport.com'
  - id6.me
  - open.e.189.cn
  - mdn.open.wo.cn
  - auth.wosms.cn
  - '*.jegotrip.com.cn'
  - '*.icitymobile.mobi'
  - '*.pingan.com.cn'
  - '*.cmbchina.com'
  - pool.ntp.org
  - '*.pool.ntp.org'
  - ntp.*.com
  - time.*.com
  - ntp?.*.com
  - time?.*.com
  - time.*.gov
  - time.*.edu.cn
  - '*.ntp.org.cn'
  - PDC._msDCS.*.*
  - DC._msDCS.*.*
  - GC._msDCS.*.*
  - speedtest.cros.wr.pvp.net
  - '*.teafone.com'
  - '*.sktswe.net'
  - rtc.goodfone.co.kr
  - '*.chattti.com'
  - '+.push.apple.com'
proxy-server-nameserver:
  - https://223.5.5.5/dns-query
  - https://doh.pub/dns-query
nameserver-policy:
  '*.tmall.com': 223.5.5.5
  '*.taobao.com': 223.5.5.5
  '*.alicdn.com': 223.5.5.5
  '*.aliyun.com': 223.5.5.5
  '*.alipay*.com': 223.5.5.5
  '*.alibaba*.com': 223.5.5.5
  '*.alimama*.com': 223.5.5.5
  '*.qq.com': 119.29.29.29
  '*.tencent.com': 119.29.29.29
  '*.weixin.com': 119.29.29.29
  dns.alidns.com: quic://223.5.5.5:853
  dot.pub: 119.29.29.29
  doh.pub: 119.29.29.29
  dns.pub: 119.29.29.29
  doh.360.cn: 101.198.198.198
  'geosite:cn,private':
    - https://223.5.5.5/dns-query
    - https://doh.pub/dns-query
  'geosite:geolocation-!cn':
    - tls://8.8.8.8
    - tls://1.1.1.1
nameserver:
- https://223.5.5.5/dns-query
- https://doh.pub/dns-query
