latencyUrl: http://cp.cloudflare.com/generate_204
latencyTimeout: 3000
proxyOrder: 0
connProfile: true
theme: 2
systemTheme: true
bypassText: |
  bypass:
    - qq.com
    - 'music.163.com' # 网易云域名1
    - '*.music.126.net' # 网易云域名2
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
showNotifications: true
selectAfterUpdated: false
mixinText: |-
  mixin: # object
    dns:
      enable: true
      ipv6: false
      default-nameserver:
        - 223.5.5.5
        - 119.29.29.29
        - 1.1.1.1
        - 8.8.8.8
      enhanced-mode: redir-host # or fake-ip
      nameserver:
        - https://dns.alidns.com/dns-query # Ali DoH
  #     - https://dns.alidns.com/resolve
        - https://dns.pub/dns-query # Tencent DoH
        - https://doh.opendns.com/dns-query # Cisco OpenDNS DoH
        - https://dns.rubyfish.cn/dns-query # Rubyfish DoH
      fallback:
  #     - https://1.0.0.1/dns-query # Cloudflare DoH
  #     - https://1.1.1.1/dns-query # Cloudflare DoH
        - https://cloudflare-dns.com/dns-query # Cloudflare DoH
        - https://public.dns.iij.jp/dns-query
        - https://dns.twnic.tw/dns-query
        - https://dns.google/dns-query # Google DoH
        - https://dns.quad9.net:5053/dns-query # IBM Quad9 DNS
  #     - https://dns.google/resolve
  #     - https://dns.nextdns.io/6a9581 # NextDNS DoH
  #     - tls://1.0.0.1:853 # Cloudflare DoT
  #     - tls://1.1.1.1:853 # Cloudflare DoT
        - tls://cloudflare-dns.com:853  # Cloudflare DoT
        - tls://dns.rubyfish.cn:853 # Rubyfish DoT
        - tls://dns.google:853 # Google DoT
  #     - tls://dns.adguard.com:853 # Adguard DoT
  #     - tls://6a9581.dns.nextdns.io # NextDNS DoT
      fallback-filter:
        geoip: true # Default
        ipcidr: # 在这个网段内的 IP 地址会被考虑为污染的 IP
          - 0.0.0.0/32
          - 127.0.0.1/32
          - 240.0.0.0/4
        domain:
          - +.google.com
          - +.facebook.com
          - +.twitter.com
          - +.youtube.com
          - +.xn--ngstr-lra8j.com
          - +.google.cn
          - +.googleapis.cn
          - +.gvt1.com
    tun: # 需要开启 Service Mode
      enable: true
      stack: system
      dns-hijack:
        - 198.18.0.2:53
      auto-route: true
      auto-detect-interface: true # 自动检测出口网卡
connMode: true
showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
proxyItemWidth: ""
showProxyFilter: false
shortcutRuleMode: ""
shortcutGlobalMode: ""
shortcutSystemProxy: ""
editor: 0
fontFamily: Avenir Light
connProxy: 1
iconSpeed: true
trayColorTransparent: false
trayText: 上善若水，厚德载物。
shortcutRunTrayScript: ""
hideUnselectableGroup: false
connChainType: 2
runTimeFormat: "hh : mm : ss"
