latencyUrl: http://cp.cloudflare.com/generate_204
latencyTimeout: 3000
proxyOrder: 0
connProfile: true
theme: 2
systemTheme: true
bypassText: |
  bypass:
    - qq.com
    - 'music.163.com' # 网易云域名1
    - '*.music.126.net' # 网易云域名2
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
showNotifications: true
selectAfterUpdated: false
mixinText: |-
  mixin: # object
    hosts:
      'api-bg.vercel.app': '76.223.126.88'
    dns:
      enable: true
      ipv6: false
      default-nameserver:
        - 223.5.5.5
        - 119.29.29.29
        - 8.8.8.8
  #   interface-name: 以太网
      enhanced-mode: redir-host # or fake-ip
      nameserver:
        - https://dns.alidns.com/dns-query
        - https://doh.pub/dns-query
        - https://dns.rubyfish.cn/dns-query
      fallback:
        - https://public.dns.iij.jp/dns-query
        - https://jp.tiar.app/dns-query
        - https://dns.switch.ch/dns-query
        - https://dns.east.comss.one/dns-query
        - tls://public.dns.iij.jp
        - tls://jp.tiar.app
        - tls://dns.switch.ch
        - tls://dns.east.comss.one
      fallback-filter:
        geoip: true # Default
        ipcidr: # 在这个网段内的 IP 地址会被考虑为污染的 IP
          - 0.0.0.0/32
          - 127.0.0.1/32
          - 240.0.0.0/4
        domain:
          - +.google.com
          - +.facebook.com
          - +.twitter.com
          - +.youtube.com
          - +.xn--ngstr-lra8j.com
          - +.google.cn
          - +.googleapis.cn
          - +.gvt1.com
    tun: # 需要开启 Service Mode
      enable: true
      stack: system
      dns-hijack:
        - 198.18.0.2:53
      auto-route: true
      auto-detect-interface: true # 自动检测出口网卡
connMode: true
showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
proxyItemWidth: ""
showProxyFilter: false
shortcutRuleMode: ""
shortcutGlobalMode: ""
shortcutSystemProxy: ""
editor: 0
fontFamily: Avenir Light
connProxy: 1
iconSpeed: true
trayColorTransparent: false
trayText: "Hovic "
shortcutRunTrayScript: ""
hideUnselectableGroup: true
connChainType: 2
runTimeFormat: "hh : mm : ss"
