showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
theme: 0
showNotifications: true
systemTheme: true
latencyUrl: http://cp.cloudflare.com/generate_204
hideUnselectableGroup: false
fontFamily: Avenir Light
bypassText: |-
  bypass:
    - localhost
    - <local>
    - '*.local'
    - passenger.t3go.cn
    - e.crashlytics.com
    - captive.apple.com
    - app.yinxiang.com
    - injections.adguard.org
    - local.adguard.org
    - cable.auth.com
    - www.baidu.com
    - yunbusiness.ccb.com
    - 10.0.0.0/8
    - 100.64.0.0/10
    - 127.0.0.0/8
    - 169.254.0.0/16
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 224.0.0.0/3
    - ::1/128
    - fc00::/7
    - fd00::/8
    - fe80::/10
    - ff00::/8
    - 2001::/32
    - 2001:db8::/32
    - 2002::/16
    - ::ffff:0:0:0:0/1
    - ::ffff:128:0:0:0/1
mixinText: |-
  mixin: # object
    ipv6: true
    profile:
      tracing: false
      store-fake-ip: true
    hosts:
      'router.asus.com': 192.168.186.1
      'gist.github.com': 52.69.186.44
    dns:
      enable: true
      ipv6: true
      listen: 127.0.0.1:8686
      nameserver-policy:
        '*.tw': 1.1.1.1
        'testflight.apple.com': 8.8.8.8
        '*.tmall.com': 223.5.5.5
        '*.taobao.com': 223.5.5.5
        '*.alicdn.com': 223.5.5.5
        '*.aliyun.com': 223.5.5.5
        '*.alipay*.com': 223.5.5.5
        '*.alibaba*.com': 223.5.5.5
        '*.alimama*.com': 223.5.5.5
        '*.qq.com': 119.29.29.29
        '*.tencent.com': 119.29.29.29
        '*.weixin.com': 119.29.29.29
        '*.qpic.cn': 119.29.29.29
        '*.jd.com': 119.29.29.29
        '*.bilibili.com': 119.29.29.29
        'hdslb.com': 119.29.29.29
        '*.163.com': 119.29.29.29
        '*.126.com': 119.29.29.29
        '*.126.net': 119.29.29.29
        '*.127.net': 119.29.29.29
        '*.netease.com': 119.29.29.29
        '*.10010.com': 119.29.29.29
        '*.unicompayment.com': 119.29.29.29
        '*.vercel.app': 119.29.29.29
        '*.vercel.com': 119.29.29.29
        '*.ximalaya.com': 119.29.29.29
        '*.baidu.com': 119.29.29.29
        '*.bdstatic.com': 119.29.29.29
      enhanced-mode: fake-ip
      fake-ip-range: 198.18.0.1/16
      use-hosts: true
      fake-ip-filter: # fake ip 白名单
      - '*.lan'
      - cable.auth.com
      - '*.msftconnecttest.com'
      - '*.msftncsi.com'
      - network-test.debian.org
      - detectportal.firefox.com
      - resolver1.opendns.com
      - '*.*.*.srv.nintendo.net'
      - '*.*.stun.playstation.net'
      - xbox.*.*.microsoft.com
      - '*.*.xboxlive.com'
      - stun.*.*.*
      - stun.*.*
      - localhost.*.qq.com
      - '*.logon.battlenet.com.cn'
      - '*.logon.battle.net'
      - '*.blzstatic.cn'
      - music.163.com
      - '*.music.163.com'
      - '*.126.net'
      - musicapi.taihe.com
      - music.taihe.com
      - songsearch.kugou.com
      - trackercdn.kugou.com
      - '*.kuwo.cn'
      - api-jooxtt.sanook.com
      - api.joox.com
      - joox.com
      - y.qq.com
      - '*.y.qq.com'
      - streamoc.music.tc.qq.com
      - mobileoc.music.tc.qq.com
      - isure.stream.qqmusic.qq.com
      - dl.stream.qqmusic.qq.com
      - aqqmusic.tc.qq.com
      - amobile.music.tc.qq.com
      - '*.xiami.com'
      - '*.music.migu.cn'
      - music.migu.cn
      - proxy.golang.org
      - '*.mcdn.bilivideo.cn'
      - '*.cmpassport.com'
      - id6.me
      - open.e.189.cn
      - mdn.open.wo.cn
      - auth.wosms.cn
      - '*.jegotrip.com.cn'
      - '*.icitymobile.mobi'
      - '*.pingan.com.cn'
      - '*.cmbchina.com'
      - pool.ntp.org
      - '*.pool.ntp.org'
      - ntp.*.com
      - time.*.com
      - ntp?.*.com
      - time?.*.com
      - time.*.gov
      - time.*.edu.cn
      - '*.ntp.org.cn'
      - PDC._msDCS.*.*
      - DC._msDCS.*.*
      - GC._msDCS.*.*
      - speedtest.cros.wr.pvp.net
      nameserver:
        - 223.5.5.5
        - 119.29.29.29
        - "[2400:3200::1]:53"
        - "[240C::6666]:53"
      fallback:
        - 8.8.8.8
        - 1.1.1.1
        - 94.140.14.14
        - "[2001:4860:4860::8888]:53"
      fallback-filter:
        geoip: true
        geoip-core: CN
        ipcidr: # 在这个网段内的 IP 地址会被考虑为被污染的 IP
        domain:
          - +.google.com
          - +.facebook.com
          - +.twitter.com
          - +.youtube.com
          - +.xn--ngstr-lra8j.com
          - +.google.cn
          - +.googleapis.cn
          - +.gvt1.com
          - +.github.com
          - +.githubusercontent.com
    tun:
      enable: true
      stack: system
      dns-hijack:
        - 198.18.0.2:53
      auto-route: true
      auto-detect-interface: true
connProxy: 2
connProfile: true
connMode: true
connChainType: 2
editor: 0
mixinType: 0
profileParsersText: >-
  parsers: # array
    - reg: .?
      yaml:
        prepend-rules:
          - SCRIPT,p2pshit,REJECT
          - SCRIPT,tcpp2pshit,REJECT
          - SCRIPT,ytbquic,REJECT
        mix-object:
          script:
            shortcuts:
              p2pshit: network == 'udp' and ('bilibili' in host or 'mcdn' in host or 'douyu' in host)
              tcpp2pshit: network == 'tcp' and 'stun' in host and 'douyu' in host
              ytbquic: network == 'udp' and dst_port == 443 and 'googlevideo' in host
trayOrders:
  - - icon
  - - status
    - traffic
    - text
trayColorTransparent: false
useSystemEmoji: true
hideTrayIcon: false
logPreloadLineCount: 0
childProcessText: "processes: # array\r

  \  - command: subconverter.exe\r

  \    options:\r

  \      cwd: C:\\Tools\\subconverter\r

  \    log: true"
specifyHttpProxyProtocol: false
connShowProcess: true
