showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
theme: 0
showNotifications: true
systemTheme: true
latencyUrl: http://cp.cloudflare.com/generate_204
hideUnselectableGroup: true
fontFamily: Avenir Light
bypassText: |-
  bypass:
    - qq.com
    - 'music.163.com' # 网易云域名1
    - '*.music.126.net' # 网易云域名2
    - localhost
    - 127.*
    - 10.*
    - 172.16.*
    - 172.17.*
    - 172.18.*
    - 172.19.*
    - 172.20.*
    - 172.21.*
    - 172.22.*
    - 172.23.*
    - 172.24.*
    - 172.25.*
    - 172.26.*
    - 172.27.*
    - 172.28.*
    - 172.29.*
    - 172.30.*
    - 172.31.*
    - 192.168.*
    - <local>
mixinText: |-
  mixin: # object
    hosts:
      'router.asus.com': 192.168.186.1
    dns:
      enable: true
      ipv6: false
      listen: 127.0.0.1:53
      nameserver-policy:
        '*.tw': 1.1.1.1
        'testflight.apple.com': 8.8.8.8
        '*.tmall.com': 223.5.5.5
        '*.taobao.com': 223.5.5.5
        '*.alicdn.com': 223.5.5.5
        '*.aliyun.com': 223.5.5.5
        '*.alipay*.com': 223.5.5.5
        '*.alibaba*.com': 223.5.5.5
        '*.alimama*.com': 223.5.5.5
        '*.qq.com': 119.29.29.29
        '*.tencent.com': 119.29.29.29
        '*.weixin.com': 119.29.29.29
        '*.qpic.cn': 119.29.29.29
        '*.jd.com': 119.29.29.29
        '*.bilibili.com': 119.29.29.29
        'hdslb.com': 119.29.29.29
        '*.163.com': 119.29.29.29
        '*.126.com': 119.29.29.29
        '*.126.net': 119.29.29.29
        '*.127.net': 119.29.29.29
        '*.netease.com': 119.29.29.29
        '*.10010.com': 119.29.29.29
        '*.unicompayment.com': 119.29.29.29
        '*.vercel.app': 119.29.29.29
        '*.vercel.com': 119.29.29.29
        '*.ximalaya.com': 119.29.29.29
        '*.baidu.com': 119.29.29.29
        '*.bdstatic.com': 119.29.29.29
      enhanced-mode: redir-host
      nameserver:
        - 223.5.5.5
        - 119.29.29.29
    tun:
      enable: true
      stack: system
      dns-hijack:
        - 198.18.0.2:53
      auto-route: true
      auto-detect-interface: true
connProxy: 2
connProfile: true
connMode: true
connChainType: 2
editor: 0
mixinType: 0
profileParsersText: |-
  parsers: # array
    - reg: .?
      yaml:
        prepend-rules:
          - SCRIPT,quic,REJECT
        mix-object:
          script:
            shortcuts:
              quic: network == 'udp' and dst_port == 443
