version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true
clash_rule_base = "https://cdn.jsdelivr.net/gh/BlueGrave/Clash@master/CFW_BaseConfig.yaml"

[[custom_groups]]
name = "DEFAULT"
type = "select"
rule = [
    "[]FlowerCloud | 香港",
    "[]FlowerCloud | 新加坡",
    "[]FlowerCloud | 日本",
    "[]FlowerCloud | 美国",
    "[]PROXY"
]

[[custom_groups]]
name = "YouTube"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "Netflix"
type = "select"
rule = [
    "[]PROXY"
]

[[custom_groups]]
name = "Emby"
type = "select"
rule = [
    "[]FlowerCloud | Emby 专用",
    "[]PROXY"
]

[[custom_groups]]
name = "Spotify"
type = "select"
rule = [
    "[]DEFAULT",
    "[]FlowerCloud | 台湾",
    "[]PROXY"
]

[[custom_groups]]
name = "PayPal"
type = "select"
rule = [
    "[]DEFAULT",
    "[]FlowerCloud | 台湾",
    "[]PROXY"
]

[[custom_groups]]
name = "GitHub"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "Google"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "Games"
type = "select"
rule = [
    "[]DIRECT",
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "AppleOS Update"
type = "select"
rule = [
    "[]DIRECT",
    "[]REJECT",
    "[]DEFAULT"
]

[[custom_groups]]
name = "Apple"
type = "select"
rule = [
    "[]DIRECT",
    "[]DEFAULT"
]

[[custom_groups]]
name = "Speedtest"
type = "select"
rule = [
    "[]DIRECT",
    ".*"
]

[[custom_groups]]
name = "PROXY"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "FlowerCloud | 香港"
type = "url-test"
rule = ["(香港高级|香港标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | 新加坡"
type = "url-test"
rule = ["(新加坡高级|新加坡标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | 日本"
type = "url-test"
rule = ["(日本高级|日本标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | 美国"
type = "url-test"
rule = ["(美国高级|美国标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | 台湾"
type = "url-test"
rule = ["(台湾高级|台湾标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | Emby 专用"
type = "url-test"
rule = ["(实验性).*(IEPL)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[rulesets]]
group = "REJECT"
ruleset = "[]SCRIPT,Quic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://cdn.jsdelivr.net/gh/BlueGrave/Clash@master/Providers/WhiteList.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://cdn.jsdelivr.net/gh/BlueGrave/Clash@master/Providers/BlackList.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://cdn.jsdelivr.net/gh/BlueGrave/Clash@master/Providers/RedList.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Lan/Lan.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Advertising/Advertising_Domain.yaml"
type = "clash-domain"

[[rulesets]]
group = "REJECT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Hijacking/Hijacking.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Privacy/Privacy_Domain.yaml"
type = "clash-domain"

[[rulesets]]
group = "REJECT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/ZhihuAds/ZhihuAds.yaml"
type = "clash-classic"

[[rulesets]]
group = "AppleOS Update"
ruleset = "https://cdn.jsdelivr.net/gh/BlueGrave/Clash@master/Providers/AppleOS_Update.yaml"
type = "clash-classic"

[[rulesets]]
group = "Netflix"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Netflix/Netflix.yaml"
type = "clash-classic"

[[rulesets]]
group = "YouTube"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/YouTube/YouTube.yaml"
type = "clash-classic"

[[rulesets]]
group = "Emby"
ruleset = "https://cdn.jsdelivr.net/gh/BlueGrave/Clash@master/Providers/Emby.yaml"
type = "clash-classic"

[[rulesets]]
group = "Spotify"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Spotify/Spotify.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/GlobalMedia/GlobalMedia.yaml"
type = "clash-classic"

[[rulesets]]
group = "PayPal"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/PayPal/PayPal.yaml"
type = "clash-classic"

[[rulesets]]
group = "GitHub"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/GitHub/GitHub.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/OneDrive/OneDrive.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleDrive/GoogleDrive.yaml"
type = "clash-classic"

[[rulesets]]
group = "GoogleVoice"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/GoogleVoice/GoogleVoice.yaml"
type = "clash-classic"

[[rulesets]]
group = "Google"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Google/Google.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Telegram/Telegram.yaml"
type = "clash-classic"

[[rulesets]]
group = "Speedtest"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Speedtest/Speedtest.yaml"
type = "clash-classic"

[[rulesets]]
group = "Games"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Steam/Steam.yaml"
type = "clash-classic"

[[rulesets]]
group = "Games"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Epic/Epic.yaml"
type = "clash-classic"

[[rulesets]]
group = "TestFlight"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/TestFlight/TestFlight.yaml"
type = "clash-classic"

[[rulesets]]
group = "Apple"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/AppStore/AppStore.yaml"
type = "clash-classic"

[[rulesets]]
group = "Apple"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Apple/Apple.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Microsoft/Microsoft.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/ChinaMedia/ChinaMedia.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Download/Download.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/PrivateTracker/PrivateTracker.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/rule/Clash/Global/Global_Domain.yaml"
type = "clash-domain"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "DEFAULT"
ruleset = "[]FINAL"