version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true
clash_rule_base = "https://raw.githubusercontent.com/BlueGrave/Clash/master/GeneralClashConfig.yaml"

[[custom_groups]]
name = "DEFAULT"
type = "select"
rule = [
    "[]Blinkload | 香港",
    "[]Blinkload | 日本",
    "[]Blinkload | 新加坡",
    "[]Blinkload | 美国",
    "[]FlowerCloud | 香港",
    "[]FlowerCloud | 新加坡",
    "[]FlowerCloud | 日本",
    "[]FlowerCloud | 美国",
    "[]PROXY"
]

[[custom_groups]]
name = "YouTube"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "Netflix"
type = "select"
rule = [
    "[]Blinkload | 新加坡",
    "[]FlowerCloud | 新加坡",
    "[]PROXY"
]

[[custom_groups]]
name = "Emby"
type = "select"
rule = [
    "[]FlowerCloud | Emby 专用",
    "[]PROXY"
]

[[custom_groups]]
name = "Spotify"
type = "select"
rule = [
    "[]DEFAULT",
    "[]Blinkload | 台湾",
    "[]FlowerCloud | 台湾",
    "[]PROXY"
]

[[custom_groups]]
name = "PayPal"
type = "select"
rule = [
    "[]DEFAULT",
    "[]Blinkload | 台湾",
    "[]FlowerCloud | 台湾",
    "[]PROXY"
]

[[custom_groups]]
name = "GitHub"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "OneDrive"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "GoogleDrive"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "Google"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "Telegram"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "Games"
type = "select"
rule = [
    "[]DIRECT",
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "AppleOS Update"
type = "select"
rule = [
    "[]DIRECT",
    "[]REJECT",
    "[]DEFAULT"
]

[[custom_groups]]
name = "Apple"
type = "select"
rule = [
    "[]DIRECT",
    "[]DEFAULT"
]

[[custom_groups]]
name = "Speedtest"
type = "select"
rule = [
    "[]DIRECT",
    ".*"
]

[[custom_groups]]
name = "PROXY"
type = "select"
rule = [".*"]

#[[custom_groups]]
name = "Blinkload | 香港"
type = "url-test"
rule = ["Hong Kong"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "Blinkload | 日本"
type = "url-test"
rule = ["Japan"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "Blinkload | 新加坡"
type = "url-test"
rule = ["Singapore"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "Blinkload | 美国"
type = "url-test"
rule = ["United States"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "Blinkload | 台湾"
type = "url-test"
rule = ["Taiwan"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | 香港"
type = "url-test"
rule = ["(香港高级|香港标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | 新加坡"
type = "url-test"
rule = ["(新加坡高级|新加坡标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | 日本"
type = "url-test"
rule = ["(日本高级|日本标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | 美国"
type = "url-test"
rule = ["(美国高级|美国标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | 台湾"
type = "url-test"
rule = ["(台湾高级|台湾标准)"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600

[[custom_groups]]
name = "FlowerCloud | Emby 专用"
type = "url-test"
rule = ["(实验性).*(IEPL)"]
url = "http://cp.cloudflare.com/generate_204"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/BlueGrave/Clash/master/Providers/WhiteList.yaml"
type = "clash-classic"

group = "REJECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Advertising/Advertising_Domain.yaml"
type = "clash-domain"

group = "DIRECT"
ruleset = "[]GEOIP,CN"

group = "DEFAULT"
ruleset = "[]FINAL"