version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true
clash_rule_base = "https://raw.githubusercontent.com/BlueGrave/Clash/master/OpenClashConfig.yaml"

[[custom_groups]]
name = "DEFAULT"
type = "fallback"
rule = [
    "[]FlowerCloud | 日本标准",
    "[]FlowerCloud | 日本高级",
    "[]FlowerCloud | 香港标准",
    "[]FlowerCloud | 香港高级",
    "[]PROXY"
]
url = "http://cp.cloudflare.com/generate_204"
interval = 300

[[custom_groups]]
name = "YouTube"
type = "fallback"
rule = [
    "[]FlowerCloud | 日本标准",
    "[]FlowerCloud | 香港标准",
    "[]PROXY"
]
url = "http://cp.cloudflare.com/generate_204"
interval = 300

[[custom_groups]]
name = "Netflix"
type = "select"
rule = ["新加坡"]

[[custom_groups]]
name = "Disney+"
type = "select"
rule = ["香港|新加坡"]

[[custom_groups]]
name = "HBO GO"
type = "select"
rule = [
    "[]FlowerCloud | 台湾",
    "[]PROXY"
]

[[custom_groups]]
name = "Spotify"
type = "select"
rule = [
    "[]FlowerCloud | 台湾",
    "[]PROXY"
]

[[custom_groups]]
name = "PayPal"
type = "select"
rule = [
    "[]FlowerCloud | 台湾",
    "[]PROXY"
]

[[custom_groups]]
name = "GoogleVoice"
type = "select"
rule = [
    "[]FlowerCloud | 美国",
    "[]PROXY"
]

[[custom_groups]]
name = "Google"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "AppleOS Update"
type = "select"
rule = [
    "[]DIRECT",
    "[]REJECT",
    "[]DEFAULT"
]

[[custom_groups]]
name = "Speedtest"
type = "select"
rule = [
    "[]DIRECT",
    ".*"
]

[[custom_groups]]
name = "PROXY"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "FlowerCloud | 日本标准"
type = "url-test"
rule = ["日本标准"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "FlowerCloud | 日本高级"
type = "url-test"
rule = ["日本高级"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "FlowerCloud | 香港标准"
type = "url-test"
rule = ["香港标准"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "FlowerCloud | 香港高级"
type = "url-test"
rule = ["香港高级"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "FlowerCloud | 美国"
type = "url-test"
rule = ["(?!.*实验).*美国"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "FlowerCloud | 台湾"
type = "url-test"
rule = ["(?!.*实验).*台湾"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/BlueGrave/Clash/master/Providers/WhiteList.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/BlueGrave/Clash/master/Providers/BlackList.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Lan/Lan.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanProgramAD.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Hijacking/Hijacking.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Privacy/Privacy_Classical.yaml"
type = "clash-classic"

[[rulesets]]
group = "REJECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ZhihuAds/ZhihuAds.yaml"
type = "clash-classic"

[[rulesets]]
group = "AppleOS Update"
ruleset = "https://raw.githubusercontent.com/BlueGrave/Clash/master/Providers/AppleOS_Update.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Download/Download.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PrivateTracker/PrivateTracker.yaml"
type = "clash-classic"

[[rulesets]]
group = "YouTube"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/YouTube/YouTube.yaml"
type = "clash-classic"

[[rulesets]]
group = "Netflix"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Netflix/Netflix.yaml"
type = "clash-classic"

[[rulesets]]
group = "Disney+"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Disney/Disney.yaml"
type = "clash-classic"

[[rulesets]]
group = "HBO GO"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/HBOHK/HBOHK.yaml"
type = "clash-classic"

[[rulesets]]
group = "HBO GO"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/StreamingMedia/Video/HBO-Asia.yaml"
type = "clash-classic"

[[rulesets]]
group = "Spotify"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Spotify/Spotify.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia.yaml"
type = "clash-classic"

[[rulesets]]
group = "PayPal"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/PayPal/PayPal.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/OneDrive/OneDrive.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://raw.githubusercontent.com/DivineEngine/Profiles/master/Clash/RuleSet/Extra/Google/GoogleDrive.yaml"
type = "clash-classic"

[[rulesets]]
group = "GoogleVoice"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GoogleVoice/GoogleVoice.yaml"
type = "clash-classic"

[[rulesets]]
group = "Google"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
type = "clash-classic"

[[rulesets]]
group = "Speedtest"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Speedtest/Speedtest.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/SteamCN/SteamCN.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Steam/Steam.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.yaml"
type = "clash-classic"

[[rulesets]]
group = "DEFAULT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/TestFlight/TestFlight.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Apple/Apple.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Microsoft/Microsoft.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/ChinaMedia/ChinaMedia.yaml"
type = "clash-classic"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "DEFAULT"
ruleset = "[]FINAL"