version = 1
[custom]
enable_rule_generator = true
overwrite_original_rules = true
clash_rule_base = "https://raw.githubusercontent.com/BlueGrave/Clash/master/ClashMiniConfig.yaml"

[[custom_groups]]
name = "DEFAULT"
type = "select"
rule = [
    "[]FlowerCloud | 日本",
    "[]FlowerCloud | 香港",
    "[]PROXY"
]

[[custom_groups]]
name = "YouTube"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "Netflix"
type = "select"
rule = [
    "[]Singapore Premium",
    "[]Netflix Relay"
]

[[custom_groups]]
name = "Disney+"
type = "select"
rule = ["^(?=.*(Singapore|Hong Kong))(?=.*Premium).*$"]

[[custom_groups]]
name = "Spotify"
type = "select"
rule = [
    "[]FlowerCloud | 台湾",
    "[]PROXY"
]

[[custom_groups]]
name = "PayPal"
type = "select"
rule = [
    "[]FlowerCloud | 台湾",
    "[]PROXY"
]

[[custom_groups]]
name = "Google"
type = "select"
rule = [
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "Games"
type = "select"
rule = [
    "[]DIRECT",
    "[]DEFAULT",
    "[]PROXY"
]

[[custom_groups]]
name = "AppleOS Update"
type = "select"
rule = [
    "[]DIRECT",
    "[]REJECT",
    "[]DEFAULT"
]

[[custom_groups]]
name = "Speedtest"
type = "select"
rule = [
    "[]DIRECT",
    ".*"
]

[[custom_groups]]
name = "PROXY"
type = "select"
rule = [".*"]

[[custom_groups]]
name = "FlowerCloud | 日本"
type = "url-test"
rule = ["((?!.*2).*日本高级)|日本标准"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "FlowerCloud | 香港"
type = "url-test"
rule = ["(?!.*实验).*香港"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "FlowerCloud | 台湾"
type = "url-test"
rule = ["(?!.*实验).*台湾"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "Singapore Premium"
type = "url-test"
rule = ["^(?=.*Singapore)(?=.*Premium).*$"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "Singapore GreenCloud"
type = "url-test"
rule = ["^(?=.*Singapore)(?=.*GreenCloud).*$"]
url = "http://cp.cloudflare.com/generate_204"
interval = 600
tolerance = 20

[[custom_groups]]
name = "Netflix Relay"
type = "relay"
rule = [
    "[]Singapore Premium",
    "[]Singapore GreenCloud"
]

[[rulesets]]
group = "DIRECT"
ruleset = "[]AND,((DOMAIN-SUFFIX,bilibili.com),(NETWORK,TCP))"

[[rulesets]]
group = "REJECT"
ruleset = "[]AND,((DOMAIN-SUFFIX,bilibili.com),(NETWORK,UDP))"

[[rulesets]]
group = "DIRECT"
ruleset = "[]AND,((DST-PORT,123/136/137-139),(NETWORK,UDP))"

[[rulesets]]
group = "REJECT"
ruleset = "[]AND,((DST-PORT,443),(GEOSITE,google),(NETWORK,UDP))"

[[rulesets]]
group = "DIRECT"
ruleset = "[]GEOIP,CN"

[[rulesets]]
group = "DEFAULT"
ruleset = "[]FINAL"