latencyUrl: http://cp.cloudflare.com/generate_204
latencyTimeout: 3000
proxyOrder: 0
connProfile: true
theme: 2
systemTheme: true
bypassText: |
  bypass:
    - qq.com
    - music.163.com
    - "*.music.126.net"
    - "*.423down.com"
    - "*.bokecc.com"
    - "*.chaipip.com"
    - "*.hrtsea.com"
    - "*.kaikeba.com"
    - "*.laomo.me"
    - "*.mpyit.com"
    - "*.cn"
    - "*.中国"
    - "*.公司"
    - "*.网络"
    - "*-cn*"
    - "*360buy*"
    - "*alicdn*"
    - "*alimama*"
    - "*alipay*"
    - "*appzapp*"
    - "*baidupcs*"
    - "*bilibili*"
    - "*ccgslb*"
    - "*chinacache*"
    - "*duobao*"
    - "*duolingo*"
    - "*jdpay*"
    - "*moke*"
    - "*qhimg*"
    - "*vpimg*"
    - "*xiami*"
    - "*xiaomi*"
    - "*.360.com"
    - "*.360kuai.com"
    - "*.360safe.com"
    - "*.dhrest.com"
    - "*.qhres.com"
    - "*.qhstatic.com"
    - "*.qhupdate.com"
    - "*.so.com"
    - "*.4399.com"
    - "*.4399pk.com"
    - "*.5054399.com"
    - "*.img4399.com"
    - "*.58.com"
    - "*.1688.com"
    - "*.aliapp.org"
    - "*.alibaba.com"
    - "*.alibabacloud.com"
    - "*.alibabausercontent.com"
    - "*.alicdn.com"
    - "*.aliexpress.com"
    - "*.aliimg.com"
    - "*.alikunlun.com"
    - "*.alipay.com"
    - "*.alipayobjects.com"
    - "*.alisoft.com"
    - "*.aliyun.com"
    - "*.aliyuncdn.com"
    - "*.aliyuncs.com"
    - "*.amap.com"
    - "*.autonavi.com"
    - "*.dingtalk.com"
    - "*.ele.me"
    - "*.hichina.com"
    - "*.mmstat.com"
    - "*.mxhichina.com"
    - "*.soku.com"
    - "*.taobao.com"
    - "*.taobaocdn.com"
    - "*.tbcache.com"
    - "*.tbcdn.com"
    - "*.tbcdn.cn"
    - "*.tmall.com"
    - "*.tmall.hk"
    - "*.ucweb.com"
    - "*.xiami.com"
    - "*.xiami.net"
    - "*.ykimg.com"
    - "*.youku.com"
    - "*.baidu.com"
    - "*.baidubcr.com"
    - "*.baidupcs.com"
    - "*.baidustatic.com"
    - "*.bcebos.com"
    - "*.bdimg.com"
    - "*.bdstatic.com"
    - "*.bdurl.net"
    - "*.hao123.com"
    - "*.hao123img.com"
    - "*.jomodns.com"
    - "*.yunjiasu-cdn.net"
    - "*.acg.tv"
    - "*.acgvideo.com"
    - "*.b23.tv"
    - "*.biliapi.com"
    - "*.biliapi.net"
    - "*.biligame.com"
    - "*.biligame.net"
    - "*.bilivideo.com"
    - "*.hdslb.com"
    - "*.im9.com"
    - "*.battle.net"
    - "*.battlenet.com"
    - "*.blizzard.com"
    - "*.bytedance.com"
    - "*.bytedance.net"
    - "*.bytedns.net"
    - "*.byteimg.com"
    - "*.feiliao.com"
    - "*.gifshow.com"
    - "*.huoshan.com"
    - "*.iesdouyin.com"
    - "*.ixigua.com"
    - "*.kspkg.com"
    - "*.pstatp.com"
    - "*.snssdk.com"
    - "*.toutiao.com"
    - "*.toutiao13.com"
    - "*.toutiaocdn.com"
    - "*.toutiaocdn.net"
    - "*.toutiaocloud.com"
    - "*.toutiaohao.com"
    - "*.toutiaohao.net"
    - "*.toutiaoimg.com"
    - "*.toutiaopage.com"
    - "*.wukong.com"
    - "*.zijieimg.com"
    - "*.zjbyte.com"
    - "*.zjcdn.com"
    - "*.cctv.com"
    - "*.cctvpic.com"
    - "*.livechina.com"
    - "*.21cn.com"
    - "*.didialift.com"
    - "*.didiglobal.com"
    - "*.udache.com"
    - "*.douyu.com"
    - "*.douyu.tv"
    - "*.douyutv.com"
    - "*.epicgames.com"
    - "*.helpshift.com"
    - "*.paragon.com"
    - "*.unrealengine.com"
    - "*.dbankcdn.com"
    - "*.hc-cdn.com"
    - "*.hicloud.com"
    - "*.huawei.com"
    - "*.huaweicloud.com"
    - "*.huaweishop.net"
    - "*.hwccpc.com"
    - "*.vmall.com"
    - "*.vmallres.com"
    - "*.iflyink.com"
    - "*.iflyrec.com"
    - "*.iflytek.com"
    - "*.71.am"
    - "*.71edge.com"
    - "*.iqiyi.com"
    - "*.iqiyipic.com"
    - "*.ppsimg.com"
    - "*.qiyi.com"
    - "*.qiyipic.com"
    - "*.qy.net"
    - "*.360buy.com"
    - "*.360buyimg.com"
    - "*.jcloudcs.com"
    - "*.jd.com"
    - "*.jd.hk"
    - "*.jdcloud.com"
    - "*.jdpay.com"
    - "*.paipai.com"
    - "*.iciba.com"
    - "*.ksosoft.com"
    - "*.ksyun.com"
    - "*.kuaishou.com"
    - "*.yximgs.com"
    - "*.meitu.com"
    - "*.meitudata.com"
    - "*.meitustat.com"
    - "*.meipai.com"
    - "*.le.com"
    - "*.lecloud.com"
    - "*.letv.com"
    - "*.letvcloud.com"
    - "*.letvimg.com"
    - "*.letvlive.com"
    - "*.letvstore.com"
    - "*.hitv.com"
    - "*.hunantv.com"
    - "*.mgtv.com"
    - "*.duokan.com"
    - "*.mi-img.com"
    - "*.mi.com"
    - "*.miui.com"
    - "*.xiaomi.com"
    - "*.xiaomi.net"
    - "*.xiaomicp.com"
    - "*.126.com"
    - "*.126.net"
    - "*.127.net"
    - "*.163.com"
    - "*.163yun.com"
    - "*.lofter.com"
    - "*.netease.com"
    - "*.ydstatic.com"
    - "*.youdao.com"
    - "*.pplive.com"
    - "*.pptv.com"
    - "*.pinduoduo.com"
    - "*.yangkeduo.com"
    - "*.leju.com"
    - "*.miaopai.com"
    - "*.sina.com"
    - "*.sinaapp.com"
    - "*.sinaimg.com"
    - "*.weibo.com"
    - "*.weibocdn.com"
    - "*.xiaoka.tv"
    - "*.go2map.com"
    - "*.sogo.com"
    - "*.sogou.com"
    - "*.sogoucdn.com"
    - "*.sohu-inc.com"
    - "*.sohu.com"
    - "*.sohucs.com"
    - "*.sohuno.com"
    - "*.sohurdc.com"
    - "*.v-56.com"
    - "*.playstation.com"
    - "*.playstation.net"
    - "*.playstationnetwork.com"
    - "*.sony.com"
    - "*.sonyentertainmentnetwork.com"
    - "*.amplitude.com"
    - "*.firebaseio.com"
    - "*.hockeyapp.net"
    - "*.smartmailcloud.com"
    - "*.steam-chat.com"
    - "*.steamgames.com"
    - "*.steamusercontent.com"
    - "*.steamcontent.com"
    - "*.steamstatic.com"
    - "*.steamcdn-a.akamaihd.net"
    - "*.steamstat.us"
    - "*.steampowerd.com"
    - "*.foxmail.com"
    - "*.gtimg.com"
    - "*.idqqimg.com"
    - "*.igamecj.com"
    - "*.myapp.com"
    - "*.myqcloud.com"
    - "*.qq.com"
    - "*.qqmail.com"
    - "*.qqurl.com"
    - "*.smtcdns.com"
    - "*.smtcdns.net"
    - "*.soso.com"
    - "*.tencent-cloud.net"
    - "*.tencent.com"
    - "*.tencentmind.com"
    - "*.tenpay.com"
    - "*.wechat.com"
    - "*.weixin.com"
    - "*.weiyun.com"
    - "*.appsimg.com"
    - "*.appvipshop.com"
    - "*.vip.com"
    - "*.vipstatic.com"
    - "*.ximalaya.com"
    - "*.xmcdn.com"
    - "*.00cdn.com"
    - "*.88cdn.com"
    - "*.kanimg.com"
    - "*.kankan.com"
    - "*.p2cdn.com"
    - "*.sandai.net"
    - "*.thundercdn.com"
    - "*.xunlei.com"
    - "*.got001.com"
    - "*.jstucdn.com"
    - "*.zimuzu.io"
    - "*.zimuzu.tv"
    - "*.zmz001.com"
    - "*.zmz002.com"
    - "*.zmz003.com"
    - "*.zmz004.com"
    - "*.zmz2019.com"
    - "*.zmzapi.com"
    - "*.zmzapi.net"
    - "*.zmzfile.com"
    - "*announce*"
    - "*torrent*"
    - "*tracker*"
    - "*.animetorrents.me"
    - "*.awesome-hd.me"
    - "*.beitai.pt"
    - "*.bittorrent.com"
    - "*.broadcasthe.net"
    - "*.chdbits.co"
    - "*.classix-unlimited.co.uk"
    - "*.empornium.me"
    - "*.gazellegames.net"
    - "*.hd4fans.org"
    - "*.hdchina.org"
    - "*.hdhome.org"
    - "*.hdsky.me"
    - "*.hdtime.org"
    - "*.hdzone.me"
    - "*.icetorrent.org"
    - "*.jpopsuki.eu"
    - "*.keepfrds.com"
    - "*.leaguehd.com"
    - "*.m-team.cc"
    - "*.madsrevolution.net"
    - "*.msg.vg"
    - "*.nanyangpt.com"
    - "*.ncore.cc"
    - "*.open.cd"
    - "*.ourbits.club"
    - "*.passthepopcorn.me"
    - "*.privatehd.to"
    - "*.pthome.net"
    - "*.redacted.ch"
    - "*.springsunday.net"
    - "*.tjupt.org"
    - "*.totheglory.im"
    - "*.trontv.com"
    - "*.teamviewer.com"
    - "*.baomitu.com"
    - "*.bootcss.com"
    - "*.jiasule.com"
    - "*.jsdelivr.net"
    - "*.staticfile.org"
    - "*.upaiyun.com"
    - "*.12306.com"
    - "*.17173.com"
    - "*.17k.com"
    - "*.360doc.com"
    - "*.36kr.com"
    - "*.3dmgame.com"
    - "*.51cto.com"
    - "*.51job.com"
    - "*.51jobcdn.com"
    - "*.56.com"
    - "*.8686c.com"
    - "*.abchina.com"
    - "*.abercrombie.com"
    - "*.acfun.tv"
    - "*.air-matters.com"
    - "*.air-matters.io"
    - "*.aixifan.com"
    - "*.algocasts.io"
    - "*.babytree.com"
    - "*.babytreeimg.com"
    - "*.baicizhan.com"
    - "*.baidupan.com"
    - "*.baike.com"
    - "*.biqudu.com"
    - "*.biquge.com"
    - "*.bitauto.com"
    - "*.c-ctrip.com"
    - "*.camera360.com"
    - "*.cdnmama.com"
    - "*.chaoxing.com"
    - "*.che168.com"
    - "*.chinacache.net"
    - "*.chinaso.com"
    - "*.chinaz.com"
    - "*.chinaz.net"
    - "*.chuimg.com"
    - "*.cibntv.net"
    - "*.clouddn.com"
    - "*.cloudxns.net"
    - "*.cn163.net"
    - "*.cnbeta.com"
    - "*.cnbetacdn.com"
    - "*.cnblogs.com"
    - "*.cnki.net"
    - "*.cnmstl.net"
    - "*.coolapk.com"
    - "*.coolapkmarket.com"
    - "*.csdn.net"
    - "*.ctrip.com"
    - "*.dangdang.com"
    - "*.dfcfw.com"
    - "*.dianping.com"
    - "*.dilidili.wang"
    - "*.douban.com"
    - "*.doubanio.com"
    - "*.dpfile.com"
    - "*.duowan.com"
    - "*.dxycdn.com"
    - "*.dytt8.net"
    - "*.easou.com"
    - "*.eastday.com"
    - "*.eastmoney.com"
    - "*.ecitic.com"
    - "*.ewqcxz.com"
    - "*.fang.com"
    - "*.fantasy.tv"
    - "*.feng.com"
    - "*.fengkongcloud.com"
    - "*.fir.im"
    - "*.frdic.com"
    - "*.fresh-ideas.cc"
    - "*.ganji.com"
    - "*.ganjistatic1.com"
    - "*.geetest.com"
    - "*.geilicdn.com"
    - "*.godic.net"
    - "*.gravatar.com"
    - "*.guazi.com"
    - "*.gwdang.com"
    - "*.gzlzfm.com"
    - "*.haibian.com"
    - "*.haosou.com"
    - "*.hollisterco.com"
    - "*.hongxiu.com"
    - "*.huajiao.com"
    - "*.hupu.com"
    - "*.huxiucdn.com"
    - "*.huya.com"
    - "*.ifeng.com"
    - "*.ifengimg.com"
    - "*.images-amazon.com"
    - "*.infzm.com"
    - "*.ipip.net"
    - "*.it168.com"
    - "*.ithome.com"
    - "*.ixdzs.com"
    - "*.jianguoyun.com"
    - "*.jianshu.com"
    - "*.jianshu.io"
    - "*.jianshuapi.com"
    - "*.jiathis.com"
    - "*.jmstatic.com"
    - "*.jumei.com"
    - "*.kaola.com"
    - "*.knewone.com"
    - "*.koowo.com"
    - "*.ksyungslb.com"
    - "*.kuaidi100.com"
    - "*.kugou.com"
    - "*.lancdns.com"
    - "*.landiannews.com"
    - "*.lanzou.com"
    - "*.lemicp.com"
    - "*.letitfly.me"
    - "*.linkedin.com"
    - "*.lizhi.fm"
    - "*.lizhi.io"
    - "*.lizhifm.com"
    - "*.loli.net"
    - "*.luoo.net"
    - "*.lvmama.com"
    - "*.lxdns.com"
    - "*.maoyan.com"
    - "*.meilishuo.com"
    - "*.meituan.com"
    - "*.meituan.net"
    - "*.meizu.com"
    - "*.miguvideo.com"
    - "*.mobike.com"
    - "*.mogu.com"
    - "*.mogucdn.com"
    - "*.mogujie.com"
    - "*.moji.com"
    - "*.moke.com"
    - "*.msstatic.com"
    - "*.mubu.com"
    - "*.myunlu.com"
    - "*.nruan.com"
    - "*.nuomi.com"
    - "*.onedns.net"
    - "*.onlinedown.net"
    - "*.oracle.com"
    - "*.oschina.net"
    - "*.ourdvs.com"
    - "*.overcast.fm"
    - "*.paypal.com"
    - "*.polyv.net"
    - "*.qbox.me"
    - "*.qcloud.com"
    - "*.qcloudcdn.com"
    - "*.qdaily.com"
    - "*.qdmm.com"
    - "*.qhimg.com"
    - "*.qianqian.com"
    - "*.qidian.com"
    - "*.qihucdn.com"
    - "*.qin.io"
    - "*.qiniu.com"
    - "*.qiniucdn.com"
    - "*.qiniudn.com"
    - "*.qiushibaike.com"
    - "*.quanmin.tv"
    - "*.qunar.com"
    - "*.qunarzz.com"
    - "*.rarbg.to"
    - "*.repaik.com"
    - "*.rrmj.tv"
    - "*.ruguoapp.com"
    - "*.runoob.com"
    - "*.sankuai.com"
    - "*.segmentfault.com"
    - "*.sf-express.com"
    - "*.shumilou.net"
    - "*.simplecd.me"
    - "*.sm.ms"
    - "*.smzdm.com"
    - "*.snwx.com"
    - "*.soufunimg.com"
    - "*.ssl-images-amazon.com"
    - "*.sspai.com"
    - "*.startssl.com"
    - "*.suning.com"
    - "*.taihe.com"
    - "*.th-sjy.com"
    - "*.tianqi.com"
    - "*.tianqistatic.com"
    - "*.tianyancha.com"
    - "*.tianyaui.com"
    - "*.tietuku.com"
    - "*.tiexue.net"
    - "*.tmiaoo.com"
    - "*.trip.com"
    - "*.ttmeiju.com"
    - "*.tudou.com"
    - "*.tuniu.com"
    - "*.tuniucdn.com"
    - "*.umengcloud.com"
    - "*.upyun.com"
    - "*.uxengine.net"
    - "*.videocc.net"
    - "*.vmware.com"
    - "*.wandoujia.com"
    - "*.weather.com"
    - "*.weico.cc"
    - "*.weidian.com"
    - "*.weiphone.com"
    - "*.weiphone.net"
    - "*.womai.com"
    - "*.wscdns.com"
    - "*.xdrig.com"
    - "*.xhscdn.com"
    - "*.xiachufang.com"
    - "*.xiaohongshu.com"
    - "*.xiaojukeji.com"
    - "*.xinhuanet.com"
    - "*.xitek.com"
    - "*.xiumi.us"
    - "*.xslb.net"
    - "*.xueqiu.com"
    - "*.yach.me"
    - "*.yeepay.com"
    - "*.yhd.com"
    - "*.yihaodianimg.com"
    - "*.yinxiang.com"
    - "*.yinyuetai.com"
    - "*.yixia.com"
    - "*.ys168.com"
    - "*.yuewen.com"
    - "*.yy.com"
    - "*.yystatic.com"
    - "*.zealer.com"
    - "*.zhangzishi.cc"
    - "*.zhanqi.tv"
    - "*.zhaopin.com"
    - "*.zhihu.com"
    - "*.zhimg.com"
    - "*.zhongsou.com"
    - "*.zhuihd.com"
    - 127.0.0.1
    - 192.168.0.0/16
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 100.64.0.0/10
    - 17.0.0.0/8
    - localhost
    - "*.local"
    - 169.254.0.0/16
    - 224.0.0.0/4
    - 240.0.0.0/4
    - <local>
showNotifications: true
selectAfterUpdated: false
mixinText: |-
  mixin: # object
    dns:
      enable: true
      ipv6: false
      default-nameserver:
        - 223.5.5.5
        - 119.29.29.29
        - 1.1.1.1
        - 8.8.8.8
      enhanced-mode: redir-host # or fake-ip
      nameserver:
        - https://dns.alidns.com/dns-query # Ali DoH
  #     - https://dns.alidns.com/resolve
        - https://dns.pub/dns-query # Tencent DoH
        - https://doh.opendns.com/dns-query # Cisco OpenDNS DoH
        - https://dns.rubyfish.cn/dns-query # Rubyfish DoH
      fallback:
  #     - https://1.0.0.1/dns-query # Cloudflare DoH
  #     - https://1.1.1.1/dns-query # Cloudflare DoH
        - https://cloudflare-dns.com/dns-query # Cloudflare DoH
        - https://public.dns.iij.jp/dns-query
        - https://dns.twnic.tw/dns-query
        - https://dns.google/dns-query # Google DoH
        - https://dns.quad9.net:5053/dns-query # IBM Quad9 DNS
  #     - https://dns.google/resolve
  #     - https://dns.nextdns.io/6a9581 # NextDNS DoH
  #     - tls://1.0.0.1:853 # Cloudflare DoT
  #     - tls://1.1.1.1:853 # Cloudflare DoT
        - tls://cloudflare-dns.com:853  # Cloudflare DoT
        - tls://dns.rubyfish.cn:853 # Rubyfish DoT
        - tls://dns.google:853 # Google DoT
  #     - tls://dns.adguard.com:853 # Adguard DoT
  #     - tls://6a9581.dns.nextdns.io # NextDNS DoT
      fallback-filter:
        geoip: true # Default
        ipcidr: # 在这个网段内的 IP 地址会被考虑为污染的 IP
          - 0.0.0.0/32
          - 127.0.0.1/32
          - 240.0.0.0/4
        domain:
          - +.google.com
          - +.facebook.com
          - +.twitter.com
          - +.youtube.com
          - +.xn--ngstr-lra8j.com
          - +.google.cn
          - +.googleapis.cn
          - +.gvt1.com
    tun: # 需要开启 Service Mode
      enable: true
      stack: gvisor
      dns-hijack:
        - 198.18.0.2:53
      macOS-auto-route: true
      macOS-auto-detect-interface: true # 自动检测出口网卡
connMode: true
showNewVersionIcon: true
hideAfterStartup: true
randomControllerPort: true
proxyItemWidth: ""
showProxyFilter: false
shortcutRuleMode: ""
shortcutGlobalMode: ""
shortcutSystemProxy: ""
editor: 0
fontFamily: Avenir Light
connProxy: 1
iconSpeed: true
trayColorTransparent: false
trayText: 上善若水，厚德载物。
shortcutRunTrayScript: ""
hideUnselectableGroup: true
